babylon covenant signer config
cephalopodequipment/config pull request #29
Opened 2024-05-16 14:11 UTC by dbkbali

2024-05-16 15:18 UTC, mircea-c requested changes
We'll apply any changes to this after the signing test is complete.

2024-05-16 15:18 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
> +host = {{ key (print (env "CONSUL_PATH") "/btc.full_node_endpoint") }}
The btc node needs to register a consul service for this endpoint. Need to avoid hard coding these in Consul

2024-05-16 15:18 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
> +{{ with secret "static_secrets/babylon-testnet/bitcoind-node" }}
Is there some documentation for this config file? I'd like to understand what this user is for.

2024-05-16 15:18 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
> +network = "signet"
This value needs to be parametrized. An environment variable is fine

2024-05-16 15:18 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
> +host = {{ key (print (env "CONSUL_PATH") "/btc.wallet_node_endpoint") }}
Same as the full node endpoint. The wallet job needs to register an endpoint service with Consul.

2024-05-16 15:18 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
> +{{ with secret "static_secrets/babylon-testnet/bitcoind-node" }}
Same comment as the full node config. Need to understand what this is for

2024-05-16 15:18 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
> +network = "signet"
Same as full node config.

2024-05-16 15:21 UTC, mircea-c commented
I'm also not seeing the `txindex` field in here. From the babylon team:

```
For the rest of the teams: please also include the txindex=1 in your BTC Full Node config. The deployment doc has also been updated accordingly.
```

2024-05-16 15:42 UTC, dbkbali commented on babylon-testnet/covenant-signer/config.toml.tpl
> +{{ with secret "static_secrets/babylon-testnet/bitcoind-node" }}
again would have been good to discuss options here - but both the signer and full node rpc endpoints require a rpcuser and rpcpassword to access the rpc - if this can be done in a better way was looking for your suggestions

2024-05-16 15:45 UTC, dbkbali commented on babylon-testnet/covenant-signer/config.toml.tpl
> +network = "signet"
not sure what you mean hear exactly - the testnet we are currently using is signet - assuming from your comments that you want this structured with hashicorp as if we are going to production - probably quicker if we could have spent 5 minutes discussing this

2024-05-16 15:47 UTC, dbkbali commented on babylon-testnet/covenant-signer/config.toml.tpl
> +{{ with secret "static_secrets/babylon-testnet/bitcoind-node" }}
https://github.com/babylonchain/covenant-signer/blob/v0.1.0/docs/deployment.md

2024-05-16 15:55 UTC, dbkbali commented
> I'm also not seeing the `txindex` field in here. From the babylon team:
> 
> ```
> For the rest of the teams: please also include the txindex=1 in your BTC Full Node config. 
> The deployment doc has also been updated accordingly.
> ```
Again would have been good to discuss - this is included in the nomad job with a flag argument on start - bitcoin provides the option to include flags on startup or to use a config file - to avoid another artifact for the bitcoin nodes - I have opted to use the appropriate flags in the relevant nomad jobs - so for the full node nomad job the args already include "--txindex=1"

2024-05-16 16:02 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
> +host = {{ key (print (env "CONSUL_PATH") "/btc.full_node_endpoint") }}
Discussion in github is always preferable for things like this one. That way we already have documented some of these smaller design decisions :wink:

2024-05-16 16:02 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
> +network = "signet"
Same as full node config, as in this needs to be parametrized. Whatever we put in dev is always preparation for production, otherwise it's not really useful to us.

2024-05-16 16:08 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
> +{{ with secret "static_secrets/babylon-testnet/bitcoind-node" }}
We read through that document together, if you recall. There's no mention of `user` or `pass`.

They do talk about `rpcuser` and `rpcpassword` but the babylon team did not request those for the signing test, and it seems they can perform the signing request without them.

So it would be good to understand what these fields are for.

2024-05-23 17:09 UTC, dbkbali commented on babylon-testnet/covenant-signer/config.toml.tpl
> +{{ with secret "static_secrets/babylon-testnet/bitcoind-node" }}
they are rpc user and user rpc passwords the covenant signer needs these presumably for actions it will need to perform by accessing these nodes .ie checking staking transactions and signing unbounding messages

2024-05-23 23:36 UTC, mircea-c commented on babylon-testnet/bitcoin-fullnode/bitcoin-conf.toml.tpl
> +signet=1
So this conf file is hard coded for the signet network?

2024-05-23 23:53 UTC, dbkbali commented on babylon-testnet/bitcoin-fullnode/bitcoin-conf.toml.tpl
> +signet=1
yes that is the testnet babylon uses and also why I have it stored under babylon-testnet

2024-05-24 00:02 UTC, mircea-c commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    restore_wallet $wallet_name $wallet_file_path
So, does this command make a copy of the wallet file on the volume, or is it stored in RAM by the bitcoin node until it restarts?

2024-05-24 00:02 UTC, mircea-c commented on babylon-testnet/covenant-signer/config.toml.tpl
Same comment as the other config file. 

We're using the convention that configs need to be independent of the environment they are used in

2024-05-24 00:47 UTC, dbkbali commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    bitcoin-cli -rpccookiefile=/home/bitcoin/.bitcoin/.cookie -rpcconnect=$NOMAD_HOST_IP_rpc -rpcport=$NOMAD_HOST_PORT_rpc "$@" || {
I dont think this dependency is hidden as there is a clear dependency on the main task running in nomad not just the ports but also the configuration of the server cookie file etc which is set in the templated bitcoin.conf file. I will refactor so that all these variables are set from env vars for now.

2024-05-24 00:52 UTC, dbkbali commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    echo "$*"
logger is part of util-linuz package which is included by default in the base installation of linux os's. It is used to send/record messages to the linux system logs

2024-05-24 00:53 UTC, dbkbali commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    logger "$*"
logger is part of util-linuz package which is included by default in the base installation of linux os's. It is used to send/record messages to the linux system logs. So on linux - unless you need a specific version there is no need to install a seperate binary

2024-05-24 00:58 UTC, dbkbali commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    local passphrase=$1
Could you please elaborate on your reservations. I have reservations about including a limited use script in the docker file which ultimately will take 20 to 30 minutes to build every time a change or additional functionality is required -followed by testing.  Regardless the shell script will need to be stored somewhere - not clear to me what repo you wish to store it in. I would propose we leave this here for now and look at relocating this once the full scope of the testnet has been finalized and further research has been done on building the dockerfile from source.

2024-05-24 01:16 UTC, dbkbali commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    restore_wallet $wallet_name $wallet_file_path
the backup wallet.dat is stored in the main task at the $wallet_file_path - the restore wallet command does a verification of the backup wallet and if verified loads it into bitcoins wallet database - sqlite3 - which is not stored in ram. Even when restored the wallet cannot be used without being unlocked with the passphrase - which in the case of this configuration requires access to the cookie. So for the instance in the bitcoin signer - access to the wallet would require access to the cookie stored on the rpc-server or alternatively from the covenant-signer using the rpc credentials. If your question is security focused - I think we may be able to limit access to this wallet further through whitelist provisions available in the bitcoin configuration - however I plan to do more research here when we are not under time constraint to deliver on this testnet.

2024-05-24 13:40 UTC, mircea-c commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    logger "$*"
Understood. Since these containers don't actually make use of the linux system logs, we can safely remove this from here and leave the `echo` command.

Nomad and the fluentd plugin read stdout / stderr exclusively for any output.

2024-05-24 13:48 UTC, mircea-c commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    local passphrase=$1
> Could you please elaborate on your reservations.

Sure thing. Any code that we run in our infrastructure is a possible attack surface and should not be available to the public unless it's specifically made open source or it is a widely used and audited tool such as Nomad. 

I would rather we do not expose our config files either, but that's a necessary evil until we decide to start using SSH keys with our artifact blocks.

I agree that adding it in the docker image is not really a good solution, but not because of build times. That can be alleviated by just putting the file in a layer after the binary build. The main issue with that is also that it is a public image repository that anyone can download from and stick their nose in our business. This is another reason why I'm adamant about having images as close to the UNIX principle as possible.

Last, but not least, config repo is for config file templates. We've resisted the temptation to just stick anything in here for years, I'd like to keep it that way.

We'll leave this file here for the testnet, but we need to figure out a solution for mainnet for it to be moved to the infra repo.

2024-05-24 14:02 UTC, mircea-c commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    restore_wallet $wallet_name $wallet_file_path
I was asking because I'd like to understand the need to search for an existing wallet.

Also, there's logic a bit lower from here that makes a big assumption. I'll leave a comment there.

2024-05-24 14:07 UTC, mircea-c commented on babylon-testnet/bitcoin-signer/wallet-load-unlock.sh.tpl
> +    first_wallet=$(echo "$wallets" | jq -r '.[0]')
The assumption is the wallet we need is always at index `0`. Is this always the case since the wallet is stored in the file system?

2024-05-28 00:18 UTC, mircea-c approved these changes

2024-05-28 00:18 UTC, merged