Add tssigner config.toml for side protocol
cephalopodequipment/config pull request #63
Opened 2024-10-01 19:35 UTC by dpdanpittman

2024-10-23 16:57 UTC, mircea-c requested changes

2024-10-23 16:57 UTC, mircea-c commented on side-protocol/tssigner/config.toml.tpl
> +rpc = "http://192.248.150.102:18332"
This needs to be parametrized to use our own BTC node.

2024-10-23 16:57 UTC, mircea-c commented on side-protocol/tssigner/config.toml.tpl
> +grpc = "http://192.248.180.245:9090"
Same as above.

2024-11-05 03:26 UTC, dpdanpittman commented
Added parameterization to the config as requested

2024-12-10 19:44 UTC, sryps approved these changes

2024-12-10 19:44 UTC, merged